import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import questions from '../app/lib/mapa-schema.mjs';
import {prepareMap,mapPrompt,parseMap} from '../app/lib/mapa.mjs';
const html=fs.readFileSync(new URL('../docs/mapa-autoconhecimento-v0.html',import.meta.url),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(code);
const actual=vm.runInNewContext(code.slice(code.indexOf('const UNKNOWN'),code.indexOf('const KEY'))+';questions');
assert.equal(JSON.stringify(actual),JSON.stringify(questions),'Server question schema must match the UI');
const answers=Object.fromEntries(questions.filter(q=>q.type!=='text').map(q=>[q.id,q.type==='multi'?[q.options[0]]:q.options[0]]));
answers.professional='Não, quero ficar com o mapa pessoal';answers.work_use='SHOULD_NOT_BE_SENT';answers.name='PRIVATE_NAME';
const input=prepareMap({answers});
assert.ok(!mapPrompt(input).includes('SHOULD_NOT_BE_SENT'));assert.ok(!mapPrompt(input).includes('PRIVATE_NAME'));
assert.throws(()=>prepareMap({answers:[]}));assert.throws(()=>prepareMap({answers:{}}));
assert.throws(()=>prepareMap({answers:{...answers,interest:['invalid']}}));
assert.throws(()=>prepareMap({answers:{...answers,interest:['Ainda não sei','Investigar e aprender']}}));
const valid={summary:'Síntese fictícia.',insights:Array.from({length:5},()=>({title:'Uma hipótese',text:'Observe esta possibilidade.',evidence:['interest']})),experiment:{title:'Experimente observar',steps:['Observe sua rotina.'],evidence:['interest']},professional:null};
valid.zoneMap={hypothesis:'Uma hipótese para explorar.',evidence:['interest'],zones:['genialidade','excelencia','competencia','desenvolvimento'].map(key=>({key,text:'Exemplo fictício.',evidence:key==='genialidade'?['interest']:[]}))};
assert.match(parseMap(JSON.stringify(valid),input).zoneMap.zones[1].text,/faltam exemplos/);
assert.throws(()=>parseMap(JSON.stringify({...valid,zoneMap:{...valid.zoneMap,zones:[]}}),input));
assert.throws(()=>parseMap(JSON.stringify({...valid,zoneMap:{...valid.zoneMap,evidence:['missing']}}),input));
assert.equal(parseMap(JSON.stringify(valid),input).insights.length,5);
const accented=structuredClone(valid);accented.zoneMap.zones[1].key='Excelência';accented.zoneMap.zones[2].key='Competência';assert.equal(parseMap(JSON.stringify(accented),input).zoneMap.zones[1].key,'excelencia');
const translated=structuredClone(valid);translated.zoneMap.zones[1].key='excelence';translated.zoneMap.zones[2].key='competence';assert.equal(parseMap(JSON.stringify(translated),input).zoneMap.zones[2].key,'competencia');
const noEvidence=structuredClone(valid);noEvidence.zoneMap.zones[1].evidence=null;assert.match(parseMap(JSON.stringify(noEvidence),input).zoneMap.zones[1].text,/faltam exemplos/);
const duplicate=structuredClone(valid);duplicate.zoneMap.zones[2].key='Excelência';assert.throws(()=>parseMap(JSON.stringify(duplicate),input));
assert.throws(()=>parseMap('{',input));
assert.throws(()=>parseMap(JSON.stringify({...valid,insights:[{title:'x',text:'y',evidence:['missing']}]}),input));
assert.throws(()=>parseMap(JSON.stringify({...valid,experiment:{...valid.experiment,evidence:['work_use']}}),input));
assert.equal(parseMap(JSON.stringify({...valid,professional:{text:'ignored',evidence:['work_use']}}),input).professional,null);
const opted=prepareMap({answers:{...answers,professional:'Sim, quero explorar'}});
assert.ok(parseMap(JSON.stringify({...valid,professional:{text:'Explore possibilidades sem prometer renda.',evidence:['work_goal']}}),opted).professional);
assert.equal(parseMap(JSON.stringify({...valid,professional:{text:'x',evidence:['interest']}}),opted).professional,null);
console.log('PASS: syntax, schema parity, input validation, evidence, professional opt-in, malformed model responses');
